 These are supported funding model platforms

github: [babel] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [kisswdev, tdarkscorpion]
open_collective: babel # @kisswdev
custom: # https://csplay.ro/
